AllCops:
  TargetRubyVersion: 2.0.0
Documentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': default
    '%I': default
    '%r': '{}'
    '%w': default
    '%W': default
